---
- name: "Install build dependencies for nipapd"
  pkgng:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "py38-docutils"
    - "py38-sqlite3"

- name: "Get nipapd code from git"
  git:
    repo: "git://github.com/tykling/NIPAP.git"
    dest: "{{ nipap_checkout_path }}"
    version: "freebsd-support"
  register: gitresult

- name: "make and install nipapd as needed"
  shell: 'make install'
  args:
    chdir: "{{ nipap_checkout_path }}/nipap"
    executable: "/usr/local/bin/bash"
  when: gitresult is changed

- name: "Install nipapd config file"
  template:
    src: "nipapd.conf.j2"
    dest: "/usr/local/etc/nipap/nipapd.conf"
    mode: "0600"
    owner: "nipap"
    group: "nipap"

- name: "create /var/run/nipap/"
  file:
    dest: "/var/run/nipap/"
    state: "directory"
    mode: "0700"
    owner: "nipap"
    group: "nipap"

- name: "create /var/db/nipap/"
  file:
    dest: "/var/db/nipap/"
    state: "directory"
    mode: "0700"
    owner: "nipap"
    group: "nipap"

- name: "Create local auth db if needed"
  command: "/usr/local/sbin/nipap-passwd -c /usr/local/etc/nipap/nipapd.conf create-database"
  args:
    creates: "/var/db/nipap/local_auth.db"

- name: "Fix permissions of /var/db/nipap/local_auth.db"
  file:
    dest: "/var/db/nipap/local_auth.db"
    state: "file"
    mode: "0600"
    owner: "nipap"
    group: "nipap"

