---
- name: "Install pip"
  pkgng:
    name: "py38-pip"
    state: "present"

- name: "Install setuptools"
  pkgng:
    name: "py38-setuptools"
    state: "present"

- name: "Copy sqlite3.h to /usr/local/include/python2.7 because I have no idea how this works"
  command: "cp /usr/local/include/sqlite3.h /usr/local/include/python2.7"
  args:
    creates: "/usr/local/include/python2.7/sqlite3.h"

- name: "Install requirements.txt modules with pip. Install in the global py env."
  pip:
    requirements: "{{ nipap_checkout_path }}/nipap/requirements.txt"

