---
- name: "Install alertmanager"
  pkgng:
    name: "alertmanager"
    state: "present"

- name: "Make sure alertmanager data directory exists"
  file:
    path: "/var/db/alertmanager"
    state: "directory"
    owner: "alertmanager"
    group: "alertmanager"
    mode: "0755"

- name: "Install alertmanager config"
  template:
    src: "alertmanager.yml.j2"
    dest: "/usr/local/etc/alertmanager/alertmanager.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  tags:
    - "amconf"
  notify:
    - "restart alertmanager"
