---
- name: "Include any pf_vars.yml file that may exist"
  include_vars:
    file: "../include_vars/pf_vars.yml"
  ignore_errors: yes

- name: "check if pf module is loaded"
  shell: "/sbin/kldstat | grep pf.ko"
  register: pf_module_check
  ignore_errors: true

- name: "kldload pf module"
  command: "/sbin/kldload pf"
  when: pf_module_check.rc != 0

- name: "check if pflog module is loaded"
  shell: "/sbin/kldstat | grep pflog.ko"
  register: pflog_module_check
  ignore_errors: true

- name: "kldload pflog module"
  command: "/sbin/kldload pflog"
  when: pflog_module_check.rc != 0

- name: "Touch /etc/pf.conf"
  command: /usr/bin/touch /etc/pf.conf
  args:
    creates: /etc/pf.conf

- name: "Enable pf in rc.conf"
  service:
    name: "pf"
    enabled: yes
    state: started

- name: "Copy pf.conf (jail hosts)"
  template:
    src: "pf-jail.conf.j2"
    dest: "{{ pf_conf_path }}"
  when: pf_in_jail

- name: "Copy pf.conf (regular hosts and gateways)"
  template:
    src: "pf.conf.j2"
    dest: "{{ pf_conf_path }}"
  when: not pf_in_jail
  notify: "Reload pf rules"

- name: "Verify pf.conf (jail/vm hosts)"
  shell: "pfctl -n -f {{ pf_conf_path }}"

- name: "Enable pflog in rc.conf"
  service:
    name: "pflog"
    enabled: yes
    state: started
