---
- name: "Install build dependencies for nipap-cli"
  pkgng:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "py38-docutils"
  register: gitresult

- name: "make and install nipap-cli as needed"
  shell: 'make install'
  args:
    chdir: "{{ nipap_checkout_path }}/nipap-cli"
    executable: "/usr/local/bin/bash"
  when: gitresult is changed

