---
##############################################################################
### Bootstrap hosts with no Python interpreter installed
- name: "Install Python if needed"
  hosts: "all"
  become: True
  gather_facts: False
  tasks:
    - name: "Install Python"
      raw: "pkg install -y python"
      args:
        creates: "/usr/local/bin/python"


##############################################################################
### Include extra variables, first global, then group secrets, then host secrets
- name: "Include include_vars/global.yml with variables used across multiple roles"
  hosts: "all"
  tasks:
    - include_vars: "include_vars/global.yml"
      tags:
        - "always"

- name: "Include group secrets"
  hosts: "all"
  tasks:
    - name: "Check if group secrets exists in group_vars for any group this host is a member of"
      local_action: stat path="../group_vars/{{ item }}-secrets.yml"
      tags:
        - "always"
      loop: "{{ group_names }}"
      register: result
    - name: "Include group secrets when the file exists"
      include_vars: "{{ item.stat.path }}"
      tags:
        - "always"
      when: item.stat.exists
      loop: "{{ result.results }}"

- name: "Include host secrets"
  hosts: "all"
  tasks:
    - name: "Check if host secrets exists in host_vars"
      local_action: stat path="../host_vars/{{ ansible_nodename }}-secrets.yml"
      register: stat_result
      tags:
        - "always"
    - name: "Include host secrets when the file exists"
      include_vars: "../host_vars/{{ ansible_nodename }}-secrets.yml"
      tags:
        - "always"
      when: stat_result.stat.exists

##############################################################################
### base and host roles

- name: "configure basic freebsd stuff on all hosts (yes this means only freebsd for now)"
  hosts: "all"
  become: True
  roles:
    - "freebsd_base"

- name: "configure freebsd hosts (physical servers)"
  hosts: "freebsd_hosts"
  become: True
  roles:
    - "freebsd_host"

- name: "configure chyves bhyve hosts"
  hosts: "chyves_hosts"
  become: True
  roles:
    - "chyves_host"

- name: "configure vnet jail hosts"
  hosts: "jail_hosts"
  become: True
  roles:
    - "jail_host"

##############################################################################
### application roles below here
- name: "configure openvpn servers"
  hosts: "openvpn_servers"
  become: True
  roles:
    - "openvpn_server"

- name: "configure irc servers"
  hosts: "irc_servers"
  become: True
  roles:
    - "irc_server"

- name: "configure boardet servers"
  hosts: "boardet"
  become: True
  roles:
    - "boardet"

- name: "configure sphinx servers"
  hosts: "sphinx_servers"
  become: True
  roles:
    - "sphinx_server"

- name: "configure etherpad servers"
  hosts: "etherpad_servers"
  become: True
  roles:
    - "etherpad_server"

- name: "configure all nginx http and https servers"
  hosts: "nginx_servers"
  become: True
  roles:
    - "nginx_server"

- name: "configure wiki servers"
  hosts: "mediawiki_servers"
  become: True
  roles:
    - "mediawiki_server"

- name: "configure tor servers"
  hosts: "tor_servers"
  become: True
  roles:
    - "tor_server"

- name: "configure isc dhcp servers"
  hosts: "isc_dhcpd_servers"
  become: True
  roles:
    - "isc_dhcpd_server"

- name: "configure metabase servers"
  hosts: "metabase_servers"
  become: True
  roles:
    - "metabase_server"

- name: "configure PostgreSQL servers"
  hosts: "postgresql_servers"
  become: True
  roles:
    - "postgresql_server"

- name: "configure Unbound servers"
  hosts: "unbound_servers"
  become: True
  roles:
    - "unbound_server"

- name: "configure syslog-ng servers"
  hosts: "syslogng_servers"
  become: True
  roles:
    - "syslogng_server"

- name: "configure tykdnscheck servers"
  hosts: "tykdnscheck_servers"
  become: True
  roles:
    - "tykdnscheck_server"

- name: "configure tykbackup servers"
  hosts: "tykbackup_servers"
  become: True
  roles:
    - "tykbackup_server"

- name: "configure radicale servers"
  hosts: "radicale_servers"
  become: True
  roles:
    - "radicale_server"

- name: "configure prometheus servers"
  hosts: "prometheus_servers"
  become: True
  roles:
    - "prometheus_server"

- name: "configure grafana servers"
  hosts: "grafana_servers"
  become: True
  roles:
    - "grafana_server"

- name: "configure ansible servers"
  hosts: "ansible_servers"
  become: True
  roles:
    - "ansible_server"

- name: "configure mastodon servers"
  hosts: "mastodon_servers"
  become: True
  roles:
    - "mastodon_server"

- name: "configure alertmanager servers"
  hosts: "alertmanager_servers"
  become: True
  roles:
    - "alertmanager_server"

- name: "configure nfs servers"
  hosts: "nfs_servers"
  become: True
  roles:
    - "nfs_server"

- name: "configure snmp_exporter servers"
  hosts: "snmp_exporter_servers"
  become: True
  roles:
    - "snmp_exporter_server"

- name: "configure jitsi-meet servers"
  hosts: "jitsi_meet_servers"
  become: True
  roles:
    - "jitsi_meet_server"
