---
- name: "Install openvpn"
  pkgng:
    name: openvpn
    state: present
  tags: openvpn_server

- include_tasks:
    file: "easy_rsa.yml"
    apply:
      tags: "openvpn_server"
  tags: "openvpn_server"

- include_tasks:
    file: "openvpn.yml"
    apply:
      tags: "openvpn_server"
  tags: "openvpn_server"
