---
- name: "Create openvpn (default) configuration directory"
  file:
    path: /usr/local/etc/openvpn
    state: directory

- name: "Verify if the tun interface has been created"
  command: "ifconfig {{ openvpn_server_if_name }}"
  register: check_tun
  ignore_errors: True

- name: "Copy openvpn configuration file"
  template:
    src: "openvpn.conf.j2"
    dest: "/usr/local/etc/openvpn/openvpn.conf"
    owner: root

- name: "Copy openvpn startup script"
  template:
    src: "openvpn_startup.sh.j2"
    dest: "/usr/local/etc/openvpn/openvpn_startup.sh"
    owner: root
    mode: '700'

- name: "Copy openvpn shutdown script"
  template:
    src: "openvpn_shutdown.sh.j2"
    dest: "/usr/local/etc/openvpn/openvpn_shutdown.sh"
    owner: root
    mode: '700'

- name: "Create client config directory"
  file:
    path: /usr/local/etc/openvpn/client_configs
    state: directory

- name: "Copy openvpn client configuration file that uses the VPN as gw"
  template:
    src: "openvpn_client.conf.j2"
    dest: "/usr/local/etc/openvpn/client_configs/openvpn_client_with_gw.conf"
    owner: root
  vars:
    with_gateway: True

- name: "Copy openvpn client configuration file that do not use the VPN as gw"
  template:
    src: "openvpn_client.conf.j2"
    dest: "/usr/local/etc/openvpn/client_configs/openvpn_client_no_gw.conf"
    owner: root
  vars:
    with_gateway: False

- name: "Enable openvpn in rc.conf"
  service:
    name: openvpn
    enabled: yes
    state: started
