---
- name: "Install goaccess"
  pkgng:
    name: "goaccess"
    state: "present"

- name: "Create goaccess html directory"
  file:
    path: "/usr/local/www/goaccess"
    state: "directory"
    mode: "0755"

- name: "Create goaccess data directory"
  file:
    path: "/var/db/goaccess"
    state: "directory"
    mode: "0755"

- name: "Create goaccess.conf"
  template:
    src: "goaccess.conf.j2"
    dest: "/usr/local/etc/goaccess.conf"

- name: "Install script for downloading geoip db"
  copy:
    src: "download_geoip_database.sh"
    dest: "/usr/local/bin/download_geoip_database.sh"
    owner: "root"
    group: "wheel"
    mode: "0755"

- name: "Add cronjob to download fresh geoip db daily as needed"
  cron:
    name: "Download a fresh geoip db"
    hour: "3"
    minute: "0"
    job: "/usr/local/bin/download_geoip_database.sh"
    user: "root"

- name: "Install script for running goaccess"
  copy:
    src: "run-goaccess.sh"
    dest: "/usr/local/bin/run-goaccess.sh"
    owner: "root"
    group: "wheel"
    mode: "0755"

- name: "Add cronjob to run goaccess daily"
  cron:
    name: "Run goaccess on the latest logfile"
    hour: "1"
    minute: "0"
    job: "/usr/local/bin/run-goaccess.sh"
    user: "root"
