---
- include_tasks: "nginx.yml"
- include_tasks: "syslog.yml"
- include_tasks: "directories.yml"
- include_tasks: "configs.yml"
  tags:
    - "vhosts"
- include_tasks:
    file: "dehydrated.yml"
    apply:
      tags: dehydrated
  tags: dehydrated
  when: nginx_proxy

- include_tasks: "goaccess.yml"
  when:
    - nginx_goaccess
    - nginx_proxy
- include_tasks: "nginx_exporter.yml"
