---
- name: "Install nginx_exporter"
  pkgng:
    name: "nginx-prometheus-exporter"
    state: "present"
  notify: "restart nginx_exporter"

- name: "Create supervisord.d config file to run nginx_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "nginx_exporter"
    supervisord_programs:
      - name: "nginx_exporter"
        comment: "run nginx_exporter"
        command: "/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri={{ nginx_exporter_uri }}"
        user: "nobody"
    supervisord_extra_programs: []
