---
- name: "Copy nginx OCSP priming script"
  copy:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "prime_nginx_ocsp.sh"
    dest: "/usr/local/bin/prime_nginx_ocsp.sh"

- name: "Run nginx ocsp priming script"
  command: "/usr/local/bin/prime_nginx_ocsp.sh"

- name: "Make sure hourly cronjob for nginx ocsp priming is in place"
  cron:
    name: "nginx ocsp priming script (every hour)"
    minute: "{{ 59 |random }}"
    job: "/usr/local/bin/prime_nginx_ocsp.sh"
    cron_file: "nginx_ocsp"
    user: "nobody"
