---
- name: "Install php, nginx and other relevant packages"
  pkgng:
    name: php81,php81-pgsql,php81-extensions,php81-gd,nginx
    state: "present"

- name: "Copy boardet source php source files"
  copy:
    src: brobye_dk
    dest: /usr/local/www/
    owner: root

- name: "copy index.php file with proper credentials"
  template:
    src: "index.php.j2"
    dest: "/usr/local/www/brobye_dk/index.php"
    owner: root

- name: "copy splash.php file with proper credentials"
  template:    
    src: "splash.php.j2"
    dest: "/usr/local/www/brobye_dk/splash.php"
    owner: root

- name: "copy extensions.ini"
  copy:
    src: extensions.ini
    dest: /usr/local/etc/php/
    owner: root

- name: "copy nginx configuration for boardet"
  template:    
    src: "nginx.conf.j2"
    dest: "/usr/local/etc/nginx/nginx.conf"
    owner: root

- name: "copy php-fpm configuration for boardet"
  template:    
    src: "php-fpm.conf.j2"
    dest: "/usr/local/etc/php-fpm.conf"
    owner: root
     
- name: "Enable nginx in rc.conf"
  service:
    name: nginx
    enabled: yes
    state: started

- name: "Enable php-fpm in rc.conf"
  service:
    name: php-fpm
    enabled: yes
    state: started
