---
- name: "Configure /etc/resolv.conf"
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  tags:
    - dns

- name: "Configure root email forwarding in /etc/aliases"
  lineinfile:
    dest: "/etc/aliases"
    regexp: '^root:'
    line: 'root: {{ etcaliases_root_forward_email }}'
  when: etcaliases_root_forward_email is defined

- name: "Configure /etc/hosts"
  blockinfile:
    create: yes
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK /etc/hosts"
    content: "{{ etchosts }}"
  when: etchosts is defined

- name: "Configure /etc/motd"
  template:
    src: motd.j2
    dest: /etc/motd
