---
- name: "Get source code for exporter_exporter"
  git:
    repo: "https://github.com/QubitProducts/exporter_exporter"
    dest: "/root/exporter_exporter"
    force: yes
    version: "{{ exporter_exporter_version }}"
  register: gitresult

- name: "Install Go"
  pkgng:
    name: "go"
    state: "present"
  register: goresult
  when: gitresult.changed
 
- name: "Go get exporter_exporter"
  command: "go get ."
  args:
    chdir: "/root/exporter_exporter"
  environment:
    GOPATH: "/root/go"
    GOBIN: "/usr/local/bin"
  when: gitresult.changed

- name: "Remove Go build dep if we installed it"
  pkgng:
    name: "go"
    state: "absent"
  when:
    - gitresult.changed
    - goresult.changed

- name: "Install exporter_exporter config"
  template:
    src: "expexp.yml.j2"
    dest: "/usr/local/etc/expexp.yml"
    owner: "{{ prometheus_exporter_user }}"
    group: "{{ prometheus_exporter_user }}"
    mode: 0644
  notify:
    - "restart exporter_exporter"

- name: "Create exporter_exporter.d config directory"
  file:
    path: "/usr/local/etc/exporter_exporter.d"
    state: "directory"

- name: "Create supervisord.d config file to run exporter_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "exporter_exporter"
    supervisord_programs:
      - name: "exporter_exporter"
        comment: "run exporter_exporter"
        # FIXME: We have disabled tls for now while refactoring.
        #command: "/usr/local/bin/exporter_exporter -config.file=/usr/local/etc/expexp.yml -config.dirs=/usr/local/etc/exporter_exporter.d -web.listen-address= -web.tls.listen-address={{ exporter_exporter_listen_address }} -web.tls.cert={{ certgrinder_home }}/certificates/{{ ansible_nodename }}-chain.rsa.crt -web.tls.key {{ certgrinder_home }}/certificates/{{ ansible_nodename }}-keypair.rsa.key -web.proxy-path={{ exporter_exporter_proxy_path }} -web.telemetry-path={{ exporter_exporter_telemetry_path }}"
        command: "/usr/local/bin/exporter_exporter -config.file=/usr/local/etc/expexp.yml -config.dirs=/usr/local/etc/exporter_exporter.d -web.listen-address={{ exporter_exporter_listen_address }} -web.proxy-path={{ exporter_exporter_proxy_path }} -web.telemetry-path={{ exporter_exporter_telemetry_path }}"
        user: "{{ prometheus_exporter_user }}"
    supervisord_extra_programs: []
