---
- name: "Copy smokeping_prober binary"
  copy:
    src: "smokeping_prober"
    dest: "/usr/local/bin/smokeping_prober"
    owner: "root"
    group: "wheel"
    mode: "755"
  notify: "restart smokeping_prober"

- name: "Create supervisord.d config file to run smokeping_prober for enabled FIBs"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "smokeping_prober"
    supervisord_programs:
      - name: "smokeping_prober_fib{{ fib }}"
        comment: "run smokeping_prober for fib {{ fib }}"
        command: "/usr/sbin/setfib {{ fib }} /usr/local/bin/smokeping_prober --privileged --ping.interval={{ prometheus_smokeping_interval }} --log.format='logger:stderr?json=true' --web.listen-address=':{{ loop_idx + 9374 }}' {{ prometheus_smokeping_targets|join(' ') }}"
        user: "root"
    supervisord_extra_programs: []
  loop: "{{ prometheus_smokeping_fibs }}"
  loop_control:
    loop_var: "fib"
    index_var: "loop_idx"
