---
- name: "Install pip, setuptools, virtualenv for mobile_modem_exporter"
  pkgng:
    name:
      - "py38-pip"
      - "py38-setuptools"
      - "py38-virtualenv"
    state: "present"

- name: "Install mobile_modem_exporter in virtualenv"
  pip:
    name: "mobile_modem_exporter"
    virtualenv: "/usr/local/mobile_modem_exporter_venv"

- name: "Create a symbolic link for mobile_modem_exporter"
  file:
    src: "/usr/local/mobile_modem_exporter_venv/bin/mobile_modem_exporter"
    dest: "/usr/local/bin/mobile_modem_exporter"
    owner: "root"
    group: "wheel"
    state: "link"

- name: "Create a symbolic link for pipeserial"
  file:
    src: "/usr/local/mobile_modem_exporter_venv/bin/pipeserial"
    dest: "/usr/local/bin/pipeserial"
    owner: "root"
    group: "wheel"
    state: "link"

- name: "Create supervisord.d config file to run mobile_modem_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "mobile_modem_exporter"
    supervisord_programs:
      - name: "mobile_modem_exporter"
        comment: "run mobile_modem_exporter"
        command: "/usr/local/bin/mobile_modem_exporter {{ node_exporter_textfile_path }}/mobile_modem.prom {{ mobile_modem_devices|join(' ') }}"
        user: "root"
    supervisord_extra_programs: []
