---
- name: "Create /etc/rc.conf.d/netif config directory"
  file:
    path: "/etc/rc.conf.d/netif"
    state: "directory"
    mode: "0755"

- name: "Configure network interfaces (Add /etc/rc.conf.d/netif/* files)"
  template:
    src: "netif.j2"
    dest: "/etc/rc.conf.d/netif/{{ item.name }}"
  with_items: "{{ network_interfaces }}"
  when: item.configure
  register: result

- name: "create network interfaces with ifconfig"
  shell: "/sbin/ifconfig {{ item.interface }}{% if item.vlan is defined %}.{{ item.vlan }}{% endif %} || /sbin/ifconfig {{ item.interface }}{% if item.vlan is defined %}.{{ item.vlan }}{% endif %} create"
  ignore_errors: True
  with_items: "{{ network_interfaces }}"
  changed_when: False
  when: item.configure

- name: "(Re-)Configure network interfaces (service netif restart $interface)"
  command: "/usr/sbin/service netif restart {{ item.0.interface }}{% if item.0.vlan is defined %}.{{ item.0.vlan }}{% endif %}"
  with_together:
    - "{{ network_interfaces }}"
    - "{{ result.results }}"
  when:
    - item.0.configure
    - item.1.changed
