---
- name: "Make sure prosody newsyslog config file exists"
  copy:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "prosody-newsyslog.conf"
    dest: "/usr/local/etc/newsyslog.conf.d/prosody"

