---
- name: "Install prosody"
  pkgng:
    name: "prosody"
    state: "present"

- name: "Install db stuff for prosody, shit port doesn't do it"
  pkgng:
    name: "lua52-luadbi"
    state: "present"

- name: "Copy prosody config file"
  template:
    src: "prosody.cfg.lua.j2"
    dest: "/usr/local/etc/prosody/prosody.cfg.lua"
    mode: "0600"
    owner: "prosody"
    group: "prosody"

- name: "Create supervisord.d config file to run prosody"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "prosody"
    supervisord_programs:
      - name: "prosody"
        comment: "run prosody"
        command: "/usr/local/bin/lua51 /usr/local/bin/prosody"
        user: "prosody"

- name: "Create prosody data directory"
  file:
    path: "{{ prosody_datadir }}"
    state: "directory"
    owner: "prosody"
    group: "prosody"

