---
- name: "Get source code for uwsgi_exporter"
  git:
    repo: "https://github.com/timonwong/uwsgi_exporter"
    dest: "/root/uwsgi_exporter"
    force: yes
    version: "{{ uwsgi_exporter_version }}"
  register: gitresult

- name: "Install Go to build uwsgi_exporter"
  pkgng:
    name: "go"
    state: "present"
  register: goresult
  when: gitresult.changed
 
- name: "Go install uwsgi_exporter"
  command: "go install github.com/timonwong/uwsgi_exporter@latest"
  when: gitresult.changed

- name: "Copy uwsgi_exporter binary to /usr/local/bin"
  copy:
   src: "/root/go/bin/uwsgi_exporter"
   dest: "/usr/local/bin/uwsgi_exporter"
   remote_src: yes
  when:
    - gitresult.changed
  notify:
    - "restart uwsgi_exporter"

- name: "Remove Go build dep if we installed it"
  pkgng:
    name: "go"
    state: "absent"
  when:
    - gitresult.changed
    - goresult.changed

- name: "Create supervisord.d config file to run uwsgi_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "uwsgi_exporter"
    supervisord_programs:
      - name: "uwsgi_exporter"
        comment: "run uwsgi_exporter"
        command: "/usr/local/bin/uwsgi_exporter --stats.uri=http://{{ ansible_nodename }}:1717"
        user: "nobody"
    supervisord_extra_programs: []
