---
- name: "Install radicale"
  pkgng:
    name: "py39-radicale"
    state: "present"

- name: "Copy radicale config"
  template:
    src: "radicale-config.j2"
    dest: "{{ radicale_configdir }}/config"
    owner: "root"
    group: "wheel"
    mode: "0644"

- name: "Copy radicale rights config"
  template:
    src: "radicale-rights.j2"
    dest: "{{ radicale_configdir }}/rights"
    owner: "root"
    group: "wheel"
    mode: "0644"

- name: "Fix permissions of radicale storage location"
  file:
    dest: "{{ radicale_datadir }}"
    owner: "radicale"
    group: "radicale"
    mode: "0700"
    state: "directory"

