---
- name: "Create /etc/rc.conf.d/jail directory"
  file:
    path: "/etc/rc.conf.d/jail"
    state: "directory"
    mode: "0755"

- name: "Create jails filesystems with ezjail"
  command: "/usr/local/bin/ezjail-admin create {{ item.hostname }} 127.0.0.1"
  args:
    creates: "{{ ezjail_root }}/{{ item.hostname }}"
  loop: "{{ jails }}"

- name: "check if main jailstorage zfs exists"
  shell: "/sbin/zfs list {{ ezjail_jailstorage_dataset }}"
  register: ezjail_jailstorage_result
  ignore_errors: True

- name: "Create main jailstorage zfs as needed"
  command: "/sbin/zfs create -o mountpoint=none -o jailed=on {{ ezjail_jailstorage_dataset }}"
  when: ezjail_jailstorage_result.rc == 1

- name: "check if jailstorage zfs filesystems exists"
  shell: "/sbin/zfs list {{ item.1 }}"
  register: ezjail_jailstorage_results
  ignore_errors: True
  loop: "{{ jails | subelements('zfs_datasets', skip_missing=True) }}"

- name: "Create jailstorage zfs filesystems as needed"
  command: "/sbin/zfs create -o mountpoint=none -o jailed=on {{ item.0.1 }}"
  loop: "{{ jails | subelements('zfs_datasets', skip_missing=True)|zip(ezjail_jailstorage_results)|list }}"
  when: item.1 == "failed"
