---
- name: "Install py38-searx"
  pkgng:
    name: "py38-searx"
    state: "present"

- name: "Enable searx"
  sysrc:
    name: "searx_enable"
    value: "YES"

- name: "Start searx"
  service:
    name: "searx"
    state: "started"

