---
- name: "Install tor"
  pkgng:
    name: "tor"
    state: "present"

- name: "Enable tor"
  sysrc:
    name: "tor_enable"
    value: "YES"

- name: "Configure Tor"
  template:
    src: "torrc.j2"
    dest: "/usr/local/etc/tor/torrc"
  notify: "reload tor"

- name: "Install socat"
  pkgng:
    name: "socat"
    state: "present"
  tags: "tor"
