---
- name: "Install ansible"
  pkgng:
    name: "py39-ansible-core"
    state: "present"

- name: "Install ansible config deploy.sh script"
  template:
    src: "deploy.sh.j2"
    dest: "/root/deploy.sh"
    owner: "root"
    group: "wheel"
    mode: "0755"
