---
- name: "Install supervisord"
  pkgng:
    name: "py38-supervisor"
    state: "present"

- name: "Copy supervisor config"
  template:
    src: "supervisord.conf.j2"
    dest: "/usr/local/etc/supervisord.conf"
  notify:
    - "start supervisord"
    - "reread supervisord config"
    - "update supervisord config"

- name: "Create supervisord.d directory"
  file:
    path: "/usr/local/etc/supervisord.d"
    state: "directory"
    owner: "root"
    group: "wheel"
    mode: "0755"

- name: "Create supervisord.d config file to run supervisord_custom_jobs if needed"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "custom"
    supervisord_programs: "{{ supervisord_custom_jobs }}"
  when: supervisord_custom_jobs is defined

- name: "Enable supervisord"
  service:
    name: "supervisord"
    enabled: True

- name: "starting the supervisord service"
  service:
    name: "supervisord"
    state: "started"
