---
- name: "Install virtualenv"
  pkgng:
    name: "py38-virtualenv"
    state: "present"

- name: "Install pip"
  pkgng:
    name: "py38-pip"
    state: "present"

- name: "Create new virtualenv and install cryptography. Use CFLAGS and LDFLAGS env vars to force pip to use /usr/local/ ports OpenSSL include"
  pip:
    virtualenv_python: "python"
    name: "cryptography"
    virtualenv: "/usr/home/{{ certgrinderd_user }}/virtualenv"
    extra_args: '--global-option=build_ext'
  environment:
    CFLAGS: "-I/usr/local/include"
    LDFLAGS: "-L/usr/local/include"

- name: "Install certgrinderd with pip"
  pip:
    name: "certgrinderd"
    virtualenv: "/usr/home/{{ certgrinderd_user }}/virtualenv"

- name: "Create certgrinderd.conf config file"
  template:
    src: "certgrinderd.conf.j2"
    dest: "/usr/home/{{ certgrinderd_user }}/certgrinderd.conf"
    owner: "{{ certgrinderd_user }}"
    mode: "0644"

- name: "Make sure PermitUserEnvironment=CERTGRINDERD_DOMAINSETS is set in sshd_config"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitUserEnvironment="
    line: "PermitUserEnvironment=CERTGRINDERD_DOMAINSETS"
    state: present
  notify:
    - "restart sshd"
