---
- name: "Install PostgreSQL"
  pkgng:
    name: "postgresql{{ postgresql_version }}-server"
    state: "present"

- name: "Install PostgreSQL contrib"
  pkgng:
    name: "postgresql{{ postgresql_version }}-contrib"
    state: "present"

- name: "Install Postgis"
  pkgng:
    name: "{{ postgis_package }}"
    state: "present"
  when: postgresql_postgis

- name: "Make sure postgres homedir is owned by postgres:postgres"
  file:
    dest: "{{ postgresql_homedir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    state: "directory"
  notify: "reload postgresql"

- name: "Initialise PostgreSQL database"
  command: "/usr/sbin/service postgresql oneinitdb"
  args:
    creates: "{{ postgresql_datadir }}"
  notify: "reload postgresql"

- name: "Copy config file"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: "0600"
  notify: "restart postgresql"

- name: "Copy pg_hba.conf"
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_datadir }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: "0600"
  tags:
    - "pghba"
  notify: "reload postgresql"
